### ISSUE TITLE
Tables need equal column sizing by default + resizing for different device sizes

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1006] opened 2023-01-10 04:23 UTC
### Describe the Issue

In tables (e.g., https://docs.redpanda.com/docs/platform/introduction/intro-to-events/) the columns aren't equal size, and when you view the same table in mobile, you need to scroll right. Seems like tables should size columns equally by default and automatically resize for device small/med/large size.

Docusaurus: https://docusaurus.io/docs/styling-layout#mobile-view
Do we need to add this in each file for tables to size properly?

**Comment by JakeSCahill** [comment] 2023-03-30 13:14
Duplicate of #1366

**Closed by JakeSCahill** 2023-03-30 13:14 UTC
Labels: P3
