### ISSUE TITLE
Install Redpanda console edit

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#730] opened 2022-10-20 16:44 UTC
### Describe the Issue

The console installation manual has been moved to a dedicated install section, but we're lacking a bit of background to it.
It's important to add:
- What the Redpanda Console is
- When/why users need to install it

It's a good idea to take this opportunity to better stylize the page and follow other pages design. For example, we should use tabs to refer to different OSs. 

Link to the Preview that moved Redpanda Console install: 
[about](https://deploy-preview-722--redpanda-documentation.netlify.app/docs/quickstart/console-installation/)

Example for the tabs feature
https://github.com/redpanda-data/documentation/blob/dev/docs/quickstart/quick-start-linux.mdx

Additionally, the Docker install doc that tells users how to set up a 3-node cluster should include guidance on RP Console. For example, set up cluster, then install Console...see https://github.com/redpanda-data/documentation/issues/666 and https://github.com/redpanda-data/documentation/issues/665 and close these tickets as a duplicates when this is fixed.

**Comment by Feediver1** [comment] 2022-12-02 01:48
Duplicate of #593

**Closed by Feediver1** 2022-12-02 01:48 UTC
Labels: documentation, P1
