### ISSUE TITLE
update redpanda repo readme

### ISSUE THREAD

**Issue by coral-waters** [redpanda-data/documentation#159] opened 2022-02-07 12:11 UTC
The readme needs to be updated. There are a few typos, it should include a link to the documentation website, and the getting started should be reviewed and updated. In particular, the beta builds section needs updates after the product doc "installing previews" page is complete (https://docs.redpanda.com/docs/getting-started/install-preview)

readme - https://github.com/redpanda-data/redpanda#readme

**Comment by Feediver1** [comment] 2023-01-30 20:47
Duplicate of https://github.com/redpanda-data/documentation/issues/721

**Closed by Feediver1** 2023-01-30 20:47 UTC
