### ISSUE TITLE
Add Supported Platforms content

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#483] opened 2022-07-06 15:39 UTC
### Who is this for and what problem do they have today?

While this is a content gap topic (see [2Q2022 Doc Roadmap](https://docs.google.com/spreadsheets/d/1EjiE6lJBiFpO_JYIhq-Ep6faMj0C7Xc0XNNAPLJGGzA/edit#gid=1679000206)>Doc Content Gaps tab), it is slated to be added in 22.2.

New topic, Supported Platforms / Interoperability
New topic, Production Readiness

### What would you like fixed in or added to the documentation?

Supported platforms & readiness guide. See https://vectorizedio.atlassian.net/wiki/spaces/product/pages/178454531/Redpanda+Hardware+and+Software+Requirements

### Is this a new feature or a gap in the documentation?
Content gap

### Additional notes
See also: https://github.com/redpanda-data/documentation/issues/477

**Comment by Feediver1** [comment] 2023-01-30 21:11
There's a stale PR for this: https://github.com/redpanda-data/documentation/pull/512/files
@mattschumpert Any idea what is holding this up?

**Comment by Feediver1** [comment] 2023-01-31 17:21
Also posted in #product: https://redpandadata.slack.com/archives/C02FSLH3ZS9/p1675185197295079

**Comment by Feediver1** [comment] 2023-03-07 18:32
Now that you are back @AnneLeeperRP , reassigning back to you.

**Comment by micheleRP** [comment] 2023-03-14 14:08
closing as a duplicate of #927

**Closed by micheleRP** 2023-03-14 14:08 UTC
Labels: content gap, P3
