### ISSUE TITLE
Internal RP doc search results taking users to 22.11 rather than current version

### ISSUE THREAD

**Issue by Feediver1** [redpanda-data/documentation#936] opened 2022-12-13 16:05 UTC
### Describe the Issue

See https://redpandadata.slack.com/archives/C01LK3UK2K1/p1670946069995609

This has been mentioned to me multiple times in the past week. Please fix asap--we want/need search results to take readers to the current version by default.

**Comment by Deflaimun** [comment] 2023-03-08 15:49
We can write a [robots.txt file](https://developers.google.com/search/docs/crawling-indexing/robots/intro) to make google deprioritize some pages, however they still can be indexed.

If we want google to completely ignore some pages, we must add this label on them. 
![image](https://user-images.githubusercontent.com/5883505/223760663-7dc18525-f129-49fc-b665-ef4e57b1172a.png)

**Comment by JakeSCahill** [comment] 2023-03-30 13:17
Possible duplicate of #1065

**Closed** 2023-04-17 19:04 UTC
Labels: bug, P2
