### ISSUE TITLE
Differentiate rpk from redpanda

### ISSUE THREAD

**Issue by Deflaimun** [redpanda-data/documentation#952] opened 2022-12-16 16:07 UTC
### Describe the Issue

In the installation guides we never explicitly mention the difference between `rpk` and `redpanda` and when users should use one or the other. We only mention this on `rpk` 's page https://docs.redpanda.com/docs/platform/quickstart/rpk-install/

`rpk` comes bundled with `redpanda` so we should make this distinction a bit more obvious to the users specially on the getting started/install guides. 

### Updates to existing documentation

https://docs.redpanda.com/docs/platform/introduction/ (maybe?)
https://docs.redpanda.com/docs/platform/quickstart/quick-start-docker/
https://docs.redpanda.com/docs/platform/quickstart/kubernetes-qs-dev/
https://docs.redpanda.com/docs/platform/quickstart/quick-start-linux/
https://docs.redpanda.com/docs/platform/quickstart/quick-start-macos/
https://docs.redpanda.com/docs/platform/quickstart/quick-start-windows/

### More information 
https://docs.redpanda.com/docs/platform/quickstart/rpk-install/

**Comment by Feediver1** [comment] 2023-01-10 00:55
@AnneLeeperRP Please make this part of the rpk intro if not already flagged and planned in that ticket. Thanks.

**Comment by Feediver1** [comment] 2023-01-10 16:53
rpk Intro:

Introduction to rpk (Our RP provided operations management/is compatible with other Kafka tooling
         Creating a topic
         Consuming records from a topic
         Producing records to a topic
         Delete a topic
         Describe, list, or delete consumer groups

**Comment by Feediver1** [comment] 2023-01-10 16:56
@AnneLeeperRP Please provide the Estimate for this ticket. Thx

**Comment by micheleRP** [comment] 2023-03-14 17:42
closing as a duplicate of #1370. 
cc@paulo, @Feediver1

**Closed by micheleRP** 2023-03-14 17:42 UTC
Labels: content gap, P2
